name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: yarn install

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete --exclude 'node_modules'
          path: ./*
          remote_path: /var/www/crs-backend/
          remote_host: ${{ secrets.EC2_HOST }}
          remote_user: ubuntu
          remote_key: "${{ secrets.EC2_PRIVATE_KEY }}"
      - name: Install dependencies on remote server
        run: ssh -i "${{ secrets.SSH_PRIVATE_KEY }}" -o StrictHostKeyChecking=no ec2-3-133-98-205.us-east-2.compute.amazonaws.com "cd /var/www/crs-backend && yarn install"

      - name: Install PM2 on remote server
        run: ssh -i "${{ secrets.SSH_PRIVATE_KEY }}" -o StrictHostKeyChecking=no ec2-3-133-98-205.us-east-2.compute.amazonaws.com "sudo npm install -g pm2"
      - name: Start application with PM2
        run:
          ssh -i "${{ secrets.SSH_PRIVATE_KEY }}" -o StrictHostKeyChecking=no ec2-3-133-98-205.us-east-2.compute.amazonaws.com "
          cd /var/www/crs-backend &&
          pm2 start index.js --name crs-backend"
